### ISSUE TITLE
SEGVs raised when accessing a field of an non-existant structure

### ISSUE THREAD

**Issue by mikey-austin** [mikey-austin/stutter#18]
The following example illustrates a segfault when `foo::bar` is dumped:

```
$ gdb -q ./src/repl/stu
Reading symbols from ./src/repl/stu...done.
(gdb) r -Lsrc/stu -r
Starting program: /home/mikey/workspace/stu/src/repl/stu -Lsrc/stu -r
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.25-13.fc26.x86_64
stu> foo::bar

Program received signal SIGSEGV, Segmentation fault.
0x00000000004053f3 in Type_field_vector (stu=0x615010, t=1) at types.c:89
89          return stu->type_registry.field_vectors[t - SV_BUILTIN_TYPE_END];
Missing separate debuginfos, use: dnf debuginfo-install libedit-3.1-17.20160618cvs.fc26.x86_64 ncurses-libs-6.0-8.20170212.fc26.x86_64
(gdb) bt
#0  0x00000000004053f3 in Type_field_vector (stu=0x615010, t=1) at types.c:89
#1  0x000000000040541c in Type_field_index (stu=0x615010, t=1, field=0x616740) at types.c:95
#2  0x00000000004041ef in Sv_eval_structure_access (stu=0x615010, env=0x631cc0, x=0x616660) at sv.c:710
#3  0x0000000000404316 in Sv_eval (stu=0x615010, env=0x631cc0, x=0x616660) at sv.c:746
#4  0x000000000040441d in Sv_eval_list (stu=0x615010, env=0x631cc0, x=0x6164a0, new_env=0x7fffffffded8) at sv.c:773
#5  0x0000000000405732 in try (stu=0x615010, env=0x631cc0, to_eval=0x6164a0, catch=0x405ab6 <Try_default_catch_handler>, catch_arg=0x0, eval=0x40434c <Sv_eval_list>, updated=0x7fffffffded8)
    at try.c:40
#6  0x0000000000405ab0 in Try_eval_list (stu=0x615010, env=0x631cc0, to_eval=0x6164a0, catch=0x405ab6 <Try_default_catch_handler>, catch_arg=0x0, updated=0x7fffffffded8) at try.c:123
#7  0x000000000040227b in eval (stu=0x615010, arg=0x659880 "foo::bar\n", parse=0x402196 <Stu_parse_buf>, base=0x631cc0, updated=0x7fffffffded8) at stu.c:214
#8  0x0000000000402388 in Stu_eval_buf_in_env (stu=0x615010, buf=0x659880 "foo::bar\n", base=0x631cc0, updated=0x7fffffffded8) at stu.c:241
#9  0x00000000004016c2 in main (argc=3, argv=0x7fffffffdff8) at main.c:80
(gdb) quit
A debugging session is active.

        Inferior 1 [process 12485] will be killed.

Quit anyway? (y or n) y
```

**Comment by mikey-austin** [comment]
This has been fixed in 1e81383; regression test added.
